# Generated by Django 3.2.5 on 2021-07-30 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20210716_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Articles', verbose_name='Фото статьи:'),
        ),
        migrations.CreateModel(
            name='ArticleStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.articles')),
            ],
            options={
                'db_table': 'ArticleStatistic',
            },
        ),
    ]
