# Generated by Django 3.2.5 on 2021-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210730_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата изменения:'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:'),
        ),
    ]
