# Generated by Django 3.2.5 on 2021-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210730_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Фото статьи:'),
        ),
    ]
