# Generated by Django 3.2.5 on 2021-07-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/profiles/avatars/', verbose_name='Аватар:')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения:')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Пол:')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер телефона:')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес:')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер дома:')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
